version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_BASENAME=/
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge